version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: data_import_backend
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    volumes:
      - ./backend/src:/usr/src/app/src # Mount src for development hot-reloading
      - ./backend/uploads:/usr/src/app/uploads # Persistent storage for uploaded files
    env_file:
      - ./backend/.env # Load environment variables from .env file
    depends_on:
      system_mysql_db:
        condition: service_healthy # Wait for DB to be ready
    networks:
      app_network:
        # You can assign a static IP if needed, but service discovery by name is preferred
        # ipv4_address: 12.12.0.2 
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: data_import_frontend
    ports:
      - "8080:80" # Map container port 80 (nginx default) to host port 8080
    volumes:
      - ./frontend:/usr/share/nginx/html # Mount frontend files
    depends_on:
      - backend
    networks:
      app_network:
        # ipv4_address: 12.12.0.3
    restart: unless-stopped

  system_mysql_db:
    image: mysql:8.0
    container_name: system_mysql_db
    ports:
      - "3307:3306" # Map container port 3306 to host port 3307
    environment:
      MYSQL_ROOT_PASSWORD: yoursecurepassword 
      MYSQL_DATABASE: data_import_system    
    volumes:
      - system_db_data:/var/lib/mysql 
      - ./system_db_init:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      app_network:
        # ipv4_address: 12.12.0.4
    restart: unless-stopped

volumes:
  system_db_data: 

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "12.12.0.0/16"  # ตัวอย่าง: กำหนด subnet เอง
          # gateway: "12.12.0.1" # สามารถกำหนด gateway ได้ (optional)